In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score,accuracy_score

In [4]:
data=pd.read_csv(r"C:\Users\flypbox\Downloads\archive (4)\heart.csv")
data.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
9,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0


In [16]:
feature_cols=['chol','fbs','thal','trestbps','thalach','ca','exang']
x=data[feature_cols]
y=data.iloc[:,1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [17]:
# Used SVM classifier
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("accuracy : ", accuracy) 
print("-"*60)
print("classification_report : \n",classification_report(y_pred,y_test)) 
print("-"*60)
print("confuison_matrix : \n",confusion_matrix(y_test,y_pred))
print("-"*60)
print("roc_auc_score : ",roc_auc_score(y_pred,y_test))

accuracy :  0.8
------------------------------------------------------------
classification_report : 
               precision    recall  f1-score   support

           0       0.55      0.81      0.66        48
           1       0.93      0.80      0.86       157

    accuracy                           0.80       205
   macro avg       0.74      0.80      0.76       205
weighted avg       0.84      0.80      0.81       205

------------------------------------------------------------
confuison_matrix : 
 [[ 39  32]
 [  9 125]]
------------------------------------------------------------
roc_auc_score :  0.8043391719745223


In [18]:
# Used random forest classifier 
model=RandomForestClassifier(9)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("accuracy : ", accuracy) 
print("-"*60)
print("classification_report : \n",classification_report(y_pred,y_test)) 
print("-"*60)
print("confuison_matrix : \n",confusion_matrix(y_test,y_pred))
print("-"*60)
print("roc_auc_score : ",roc_auc_score(y_pred,y_test))

accuracy :  0.9853658536585366
------------------------------------------------------------
classification_report : 
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        68
           1       1.00      0.98      0.99       137

    accuracy                           0.99       205
   macro avg       0.98      0.99      0.98       205
weighted avg       0.99      0.99      0.99       205

------------------------------------------------------------
confuison_matrix : 
 [[ 68   3]
 [  0 134]]
------------------------------------------------------------
roc_auc_score :  0.9890510948905109


In [19]:
# Used Logistic regression 
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=500)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("accuracy : ", accuracy) 
print("-"*60)
print("classification_report : \n",classification_report(y_pred,y_test)) 
print("-"*60)
print("confuison_matrix : \n",confusion_matrix(y_test,y_pred))
print("-"*60)
print("roc_auc_score : ",roc_auc_score(y_pred,y_test))

accuracy :  0.6926829268292682
------------------------------------------------------------
classification_report : 
               precision    recall  f1-score   support

           0       0.20      0.70      0.31        20
           1       0.96      0.69      0.80       185

    accuracy                           0.69       205
   macro avg       0.58      0.70      0.56       205
weighted avg       0.88      0.69      0.75       205

------------------------------------------------------------
confuison_matrix : 
 [[ 14  57]
 [  6 128]]
------------------------------------------------------------
roc_auc_score :  0.6959459459459459
